### ISSUE TITLE
Milestone 2 - Work Plan

### ISSUE THREAD

**Issue by panntingg** [UBC-MDS/KMediansR#13]
- [x] Writing `distance` function.

- [x] Testing `distance` function.

- [x] Writing `kmedians` function.

- [x] Testing `kmedians` function.

- [x] Writing `summary` function.

- [x] Testing `summary` function.

Following GitHub Flow workflow:

- [x]  Create branch

- [x]  Code review and feedback

**Comment by panntingg** [comment]
All Completed!
